include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    public_member_api_docs: ignore
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    lines_longer_than_80_chars:
      - 120
