name: cacao_boardgame_helper
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  ansicolor: ^2.0.3
  dart_pre_commit: ^5.4.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  git_hooks: ^1.0.1

flutter:
  uses-material-design: true
