name: cacao_boardgame_helper
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  dynamic_height_grid_view: ^0.0.4
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_zoom_drawer: ^3.2.0
  isar:
    hosted: https://pub.isar-community.dev
    version: 3.1.8
  isar_flutter_libs:
    hosted: https://pub.isar-community.dev
    version: 3.1.8
  modal_bottom_sheet: ^3.0.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3

dev_dependencies:
  ansicolor: ^2.0.3
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  dart_pre_commit: ^5.4.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  git_hooks: ^1.0.1
  isar_generator:
    hosted: https://pub.isar-community.dev
    version: 3.1.8
  riverpod_lint: ^2.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/tiles/
    - assets/initial_data/
  fonts:
    - family: Burrito
      fonts:
        - asset: assets/fonts/burrito.ttf
    - family: Agenda
      fonts:
        - asset: assets/fonts/agenda_boldcondensed.ttf
          weight: 700
        - asset: assets/fonts/agenda_lightcondensed.ttf
          weight: 300
        - asset: assets/fonts/agenda_mediumcondensed.ttf
          weight: 500
